AllCops:
  TargetRubyVersion: 2.5

  # チェック対象外
  Exclude:
    - bin/*
    - db/schema.rb
    - vendor/**/*

# コメントはASCII文字で記述 => disable
Style/AsciiComments:
  Enabled: false

# ["a", "b", "c"] は %w表記にて記述 => disable
Style/WordArray:
  Enabled: false

# [:a, :b, :c] は %i表記にて記述 => disable
Style/SymbolArray:
  Enabled: false

# 空メソッドは1行で記述する => disable
Style/EmptyMethod:
  Enabled: false

Style/Documentation:
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Exclude:
    - spec/**/*
