version: 2.1
executors:
  default:
    working_directory: ~/qiita_trend_stock
    docker:
      - image: circleci/ruby:2.5.3
        environment:
          BUNDLE_JOBS: 4
          BUNDLE_PATH: vendor/bundle
          BUNDLE_RETRY: 3

commands:
  setup_bundle:
    description: "Setup bundle with cache"
    steps:
      - restore_cache:
          key: gem-cache-v1-{{ arch }}-{{ checksum "gems.locked" }}
      - run:
          name: Check bundle config
          command: |
            bundle -v
            bundle config
      - run:
          name: bundle install
          command: |
            # gem install bundler -v '~> 1.0'
            gem install bundler
            bundle install

  save_bundle_cache:
    description: "Setup bundle with cache"
    steps:
      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ checksum "gems.locked" }}
          paths:
            - vendor/bundle

jobs:
  test:
    executor: default
    environment:
      BUNDLE_WITHOUT: ""
      BUNDLE_CLEAN: true
    steps:
      - checkout
      - setup_bundle
      - save_bundle_cache
      - run:
          name: Test RuboCop
          command: bundle exec rubocop
      - run:
          name: Test RSpec
          command: bundle exec rspec
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: coverage

  build:
    executor: default
    environment:
      BUNDLE_WITHOUT: development
      BUNDLE_CLEAN: false
    steps:
      - checkout
      - setup_bundle
      - run:
          name: qiita trend stock
          command: bin/qiita_trend_stock

workflows:
  version: 2
  commit-workflow:
    jobs:
      - test
  scheduled-workflow:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "50 14 * * *"
          filters:
            branches:
              only:
                - master
