version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0
    branches:
      only:
        - master
    steps:
      - checkout
      - run:
          name: bundle install
          command: bundle check || bundle install
      - run:
          name: qiita trend stock
          command: ruby qiita_trend_stock.rb

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 16 * * *"
          filters:
            branches:
              only: master

    jobs:
      - build
