version: 2.0
jobs:
  test:
    working_directory: ~/qiita_trend_stock
    docker:
      - image: circleci/ruby:2.5.3
        environment:
          BUNDLE_CLEAN: true
          BUNDLE_JOBS: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLE_RETRY: 3
    steps:
      - checkout
      - restore_cache:
          key: gem-cache-v10-{{ arch }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: check bundle config
          command: |
            bundle -v
            bundle config
      - run:
          name: bundle install
          command: bundle check || (gem install bundler -v '~> 1.0' ; bundle install)
      - save_cache:
          key: gem-cache-v10-{{ arch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Test RuboCop
          command: bundle exec rubocop
      - run:
          name: Test RSpec
          command: bundle exec rspec
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
build:
    working_directory: ~/qiita_trend_stock
    docker:
      - image: circleci/ruby:2.5.3
        environment:
          BUNDLE_CLEAN: true
          BUNDLE_JOBS: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLE_RETRY: 3
          BUNDLE_WITHOUT: development
    steps:
      - checkout
      - restore_cache:
          key: gem-cache-v10-{{ arch }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: check bundle config
          command: |
            bundle -v
            bundle config
      - run:
          name: bundle install
          command: bundle check || (gem install bundler -v '~> 1.0' ; bundle install)
      - run:
          name: qiita trend stock
          command: bin/qiita_trend_stock

workflows:
  version: 2
  commit-workflow:
    jobs:
      - test
  scheduled-workflow:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "50 14 * * *"
          filters:
            branches:
              only:
                - master
