version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.0
    steps:
      - checkout
      - run:
          name: test test
          command: ruby test.rb

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only: master

    jobs:
      - build
