version: 2.0
jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.0
    steps:
      - checkout
      - run:
          name: bundle install
          command: bundle check || bundle install
      - run:
          name: test qiita trend stock
          command: bundle exec rspec spec
  build:
    docker:
      - image: circleci/ruby:2.5.0
    steps:
      - checkout
      - run:
          name: bundle install
          command: bundle check || bundle install --without development test
      - run:
          name: qiita trend stock
          command: ruby qiita_trend_stock.rb

workflows:
  version: 2
  commit-workflow:
    jobs:
      - test
  scheduled-workflow:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "57 3,7,11,15,19,23 * * *"
          filters:
            branches:
              only:
                - master
