version: 2.0
jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - restore_cache:
          key: gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}-v2
      - run:
          name: bundle install
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}-v2
          paths:
            - vendor/bundle
      - run:
          name: test qiita trend stock
          command: bundle exec rspec
  build:
    docker:
      - image: circleci/ruby:2.5.1
    steps:
      - checkout
      - restore_cache:
          key: gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}-v2
      - run:
          name: bundle install
          command: bundle check || bundle install --path vendor/bundle --without development
      - run:
          name: qiita trend stock
          command: ruby qiita_trend_stock.rb

workflows:
  version: 2
  commit-workflow:
    jobs:
      - test
  scheduled-workflow:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "57 3,7,11,15,19,23 * * *"
          filters:
            branches:
              only:
                - master
